spring:
  application:
    name: bishe
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bishe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://10.251.0.57:3331/bishe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
#    password: rootroot
    password: SOFT_sql2021
  web:
    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/Users/wjw/Desktop/test
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/root/test
  servlet:
    multipart:
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: wjw.bishe.dao
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081